name: Publish Docker Image

on:
  push:
 

jobs:
  push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest

     steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - run: docker build -t ghcr.io/denovaa/fgr534ffd:1.0 .
      - run: docker push ghcr.io/denovaa/fgr534ffd:1.0

      - run: ssh -o "StrictHostKeyChecking no"  'denovaa-fdsfsrttrt-vdpjdy6hvh3#wsbRUVU2O5TPONgSup6tzfaQQEAgSDC6@denovaa-fdsfsrttrt-vdpjdy6hvh3.ssh.ws-eu106.gitpod.io' 'cd /workspace/fdsfsrttrt && docker compose pull && docker compose up -d'
      

